#properties within this file will be applied to all the config server clients as the file name is application
---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
---
spring:
  profiles: eureka-client-adjective
words: reasonable,leaky,suspicious,ordinary,unlikely
---
spring:
  profiles: eureka-client-article
words: a,the
---
spring:
  profiles: eureka-client-noun
words: boat,book,vote,seat,backpack,partition,groundhog
---
spring:
  profiles: eureka-client-subject
words: I,You,He,She,It
---
spring:
  profiles: eureka-client-verb
words: ran,knew,had,saw,bought