spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/abhilash28abhi/Spring_Cloud
          searchPaths: ConfigData
server:
  port: 8001
# for file path use uri: file:///F:/SpringBoot/spring-cloud

# This controls which Actuator web endpoints are exposed.  
# Ordinarily, only /actuator/health and /actuator/info are exposed, 
# This permits external POST requests to trigger the refresh    
management.endpoints.web.exposure.include: health,info,bus-refresh