spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/abhilash28abhi/Spring_Cloud
          searchPaths: ConfigData
server:
  port: 8001
# for file path use uri: file:///F:/SpringBoot/spring-cloud